import fs from 'fs';
import path from 'path';

// Definition of 5 core categories, each having 200+ distinct lines
// Categories:
// 1. smooth (200+ lines)
// 2. cheesy (200+ lines)
// 3. nerdy (200+ lines)
// 4. romantic (200+ lines)
// 5. funny (200+ lines)
// Plus foodie (50+ lines) and clever (50+ lines) for extra spice!
// Total = 1,100+ lines!

interface RawLine {
  text: string;
  category: string;
  tip?: string;
}

const rawDataset: RawLine[] = [];

function add(category: string, text: string, tip?: string) {
  rawDataset.push({ text: text.trim(), category, tip });
}

// -------------------------------------------------------------
// SMOOTH (210 lines) - Confident, slick, flirty, high attraction
// -------------------------------------------------------------
const smoothLines = [
  "Are you a camera? Because every time I look at you, I smile.",
  "I was wondering if you had an extra heart, because mine was just stolen.",
  "Do you believe in love at first sight, or should I walk by again?",
  "If beauty were a crime, you'd be serving a life sentence without parole.",
  "You must be a magician, because whenever I look at you, everyone else disappears.",
  "I'm not an organ donor, but I'd gladly give you my heart.",
  "Is it hot in here, or is it just the chemistry between us?",
  "Excuse me, do you have a band-aid? Because I just scraped my knee falling for you.",
  "I thought perfection was a myth until you walked into the room.",
  "If I could rearrange the alphabet, I would put 'U' and 'I' together.",
  "Can you kiss me on the cheek so I can at least tell my friends an angel kissed me?",
  "I’m not a gambler, but I’d bet everything on making you smile tonight.",
  "Your hand looks heavy, let me hold it for you.",
  "I was going to wait for a sign, but your smile was already loud enough.",
  "I’m not usually someone who interrupts, but walking past you felt like a mistake.",
  "I was going to play it cool, but watching you from across the room was getting distracting.",
  "You look like my next favorite habit, and I have zero self-control.",
  "I don't need a map, but I definitely got lost the second you looked over here.",
  "Is your name Google? Because you have everything I’ve been searching for.",
  "Are you a campfire? Because you're hot and I want s'more of your time.",
  "If being gorgeous was a job, you’d be the top earner in this city.",
  "I’d tell you you’re pretty, but that feels like an understatement.",
  "Can I take a picture of you so Santa knows exactly what I want for Christmas?",
  "Are you made of stardust? Because your energy is out of this world.",
  "You look familiar... oh right, you're the person from my future plans.",
  "Do you have a pencil? Because I want to erase your past and write our future.",
  "Did the sun come out, or did you just look at me?",
  "I’m not a photographer, but I can definitely picture us together.",
  "If you were a teardrop, I’d never cry just so I wouldn’t lose you.",
  "I must be in a museum, because you are truly a work of art.",
  "They say nothing lasts forever, so would you be my nothing?",
  "Are you French? Because Eiffel for you hard.",
  "I didn't believe in fairy tales until I saw you standing here.",
  "Is there an airport nearby, or was that just my heart taking off?",
  "If kisses were snowflakes, I’d send you a blizzard.",
  "You have the kind of eyes people write songs about.",
  "Are you a bank loan? Because you've certainly got all my interest.",
  "Excuse me, miss, you dropped something: my jaw.",
  "I was going to say something smooth, but you took my breath away first.",
  "Do you have a name, or can I just call you mine?",
  "I'm not a psychic, but I see a lot of fun in our future.",
  "You must be tired, because you've been running through my mind all day.",
  "Are you a compass? Because without you, I'm completely lost.",
  "If you were a vegetable, you'd be a cute-cumber.",
  "I'd never play hide and seek with you because someone like you is impossible to find.",
  "Are you Jamaican? Because Jamaican me crazy.",
  "I was wondering if you're as sweet on the inside as you look on the outside.",
  "If happiness started with an 'H', why does mine begin with 'U'?",
  "I'm learning about important dates in history, when's yours?",
  "Is your dad a boxer? Because you're an absolute knockout.",
  "Do you have a sunburn or are you always this hot?",
  "I must be hunting treasures, because I just found gold.",
  "Are you a magnet? Because I'm helplessly attracted to you.",
  "I was going to say a cheesy line, but you deserve better than that. Hi, I'm yours.",
  "Did you sit in sugar? Because you have a pretty sweet vibe.",
  "I'd say God bless you, but it looks like he already did.",
  "Are you gravity? Because you keep pulling me in.",
  "My friends warned me about trouble, and here you are looking gorgeous.",
  "Is your smile on the menu? Because that's what I came here for.",
  "I’m not usually speechless, but you just broke my vocabulary.",
  "Are you lightning? Because you just made an electric impression.",
  "Can I borrow a kiss? I promise I'll give it right back.",
  "If you were words on a page, you'd be what they call fine print.",
  "Are you an oasis? Because in a room full of people, you're all I see.",
  "I must be a light bulb, because you just turned me on.",
  "If I had a nickel for every time I saw someone as stunning as you, I'd have exactly five cents.",
  "Are you a diamond? Because you shine brighter than anyone else here.",
  "You don't need makeup; perfection shouldn't be covered up.",
  "Are you my favorite song? Because I want you on repeat.",
  "I’m trying to write a love letter, but I need your number to finish it.",
  "Is it cold out, or did your smile just give me chills?",
  "I don't believe in coincidences, I believe in meeting you.",
  "Are you a shooting star? Because I'm wishing on you right now.",
  "If looks could thrill, you'd be a rollercoaster.",
  "Can I follow you home? Wait, that came out creepy—I meant on Instagram.",
  "Are you a mirror? Because I see my reflection looking happy next to you.",
  "I must be dreaming, because nobody looks this good in real life.",
  "If you were a star, you'd outshine the whole constellation.",
  "Excuse me, are you open to making someone's day? Because you just made mine.",
  "You must be an artist, because you've painted a smile on my face.",
  "Are you a sunrise? Because waking up to you would make any day better.",
  "I didn't know what perfection looked like until thirty seconds ago.",
  "Are you a mystery? Because I can't wait to figure you out.",
  "If charm were currency, you'd own the whole world.",
  "Is there a curfew here, or can I stay captivated by you all night?",
  "Are you an architect? Because you just redesigned my heart.",
  "You're like a four-leaf clover: rare, beautiful, and lucky to find.",
  "Can I buy you a drink, or would you rather just have the cash?",
  "I'm writing a book on modern wonders, can I put your picture on the cover?",
  "Are you moonlight? Because you make the darkest nights look stunning.",
  "If you were a fruit, you'd be a fineapple.",
  "I was having an average day until you walked in and ruined the curve.",
  "Are you a clock? Because every second without you feels like wasted time.",
  "I don't play chess, but you just made me lose all my pieces.",
  "You're proof that some people really are built differently.",
  "Is your dad an alien? Because there's nothing else like you on Earth.",
  "If kissing you was a sport, I'd be training for the Olympics right now.",
  "Are you a melody? Because I can't get you out of my head.",
  "I think the stars aligned tonight just so we'd cross paths.",
  "Are you champagne? Because you make everything feel like a celebration.",
  "I'd cross oceans for you, but let's start with this coffee shop.",
  "If elegance had a face, it would look identical to yours.",
  "Are you summer? Because you bring the heat wherever you go.",
  "I wasn't looking for love, but you made looking impossible to stop.",
  "You have a spark that could set a whole city on fire.",
  "Are you a prism? Because you bring color everywhere you go.",
  "If I could rate you out of 10, I'd give you an 11 and ask for your number.",
  "I'm usually shy, but staying quiet around you would be a crime.",
  "Are you velvet? Because everything about you feels smooth.",
  "I'd love to say something witty, but your eyes stole all my thoughts.",
  "You don't need a spotlight, your aura does all the work.",
  "Are you an angel, or do all the good things fall from heaven this cleanly?",
  "I think my phone is broken—it's completely missing your contact.",
  "If beauty was time, you'd be an eternity.",
  "Are you a sunset? Because watching you leaves me speechless.",
  "I'm not saying you're the prize, but anyone who has you definitely won.",
  "Are you silk? Because talking to you is effortless.",
  "I’d trade a thousand good days for one great evening with you.",
  "Are you a masterpiece? Because I could stand here staring for hours.",
  "If smiles could kill, you'd be an international assassin.",
  "I don't know what your plans are, but I hope they include me eventually.",
  "Are you a riddle? Because I'm hooked on solving you.",
  "You're the reason people look up from their phones.",
  "Are you a constellation? Because you connect all the bright points in my head.",
  "If sweetness were measured, you'd break the scale.",
  "I'd walk a thousand miles just to hear you laugh like that again.",
  "Are you poetry? Because every word you say flows like art.",
  "I'm not a gambler, but looking at you feels like hitting the jackpot.",
  "Are you an ember? Because you just sparked something in me.",
  "If I could freeze time, I'd pause right when you smiled at me.",
  "You have the kind of presence that demands a second look.",
  "Are you gold? Because you're precious and everyone's searching for you.",
  "I don't need luck when I've got the chance to talk to you.",
  "Are you an ocean breeze? Because you're refreshingly breathtaking.",
  "If I had one wish, I’d ask for five more minutes right here.",
  "You're not just a ten; you're the benchmark.",
  "Are you fire? Because staying near you is warm and exciting.",
  "I thought I had good taste until I saw you and realized I had none before.",
  "Are you a melody in 4/4 time? Because my pulse is keeping your beat.",
  "If charisma was measured in watts, you'd power a metropolis.",
  "I'd ask you the time, but every moment with you feels timeless.",
  "Are you a catalyst? Because being near you speeds up my heart rate.",
  "You don't just turn heads; you stop traffic.",
  "Are you a vintage wine? Because you look richer with every second.",
  "I’m no astronomer, but I’ve definitely found my North Star.",
  "If flirting was an art, talking to you would be my magnum opus.",
  "Are you a compass rose? Because all my directions point straight to you.",
  "I was told to follow my dreams, so do you mind if I walk with you?",
  "Are you serendipity? Because finding you wasn't planned, but it's perfect.",
  "You have a smile that could dissolve the coldest winter.",
  "Are you a mirror? Because every time you look at me, I reflect your vibe.",
  "I don't need caffeine when your glance gives me this much adrenaline.",
  "Are you a harbor? Because after today, I want to dock right here.",
  "If eyes had gravity, yours would be a black hole.",
  "You carry yourself like royalty, mind if I join your court?",
  "Are you a secret? Because keeping you to myself sounds tempting.",
  "I'm not good at holding back when someone looks this stunning.",
  "Are you a flame? Because I can't resist getting drawn in.",
  "If I wrote a poem for every time you looked fine, I'd have an encyclopedia.",
  "You're the missing puzzle piece my day didn't know it needed.",
  "Are you high fashion? Because you look like runway perfection.",
  "I’d give up sugar in my coffee if I could just have your sweet voice instead.",
  "Are you an espresso shot? Small, bold, and keeping me wide awake.",
  "If warmth had a silhouette, it would be standing right across from me.",
  "You don't need an introduction; your vibe announces you before you speak.",
  "Are you an invitation? Because I definitely want to RSVP 'Yes'.",
  "I’m not a fan of crowds, but I’d brave any room just to stand near you.",
  "Are you velvet night? Deep, mysterious, and impossible to forget.",
  "If beauty was currency, you'd be funding nations.",
  "I didn't believe in love at first glance, but you made me a quick convert.",
  "Are you a whisper? Because even in a loud room, I hear you clear as day.",
  "You make confidence look easy, and attraction look inevitable.",
  "Are you an heirloom? Because someone like you is priceless.",
  "If I had a dollar for every charming thing about you, I'd buy this whole bar.",
  "Are you an escape? Because reality faded the moment you walked in.",
  "I’m ready to bet my next paycheck that you’re as witty as you look.",
  "Are you a sparkler? Because you bring pure excitement to this room.",
  "If I could save one memory from this week, it’d be you smiling right now.",
  "You have an effortless charm that words can barely capture.",
  "Are you silk satin? Because being around you feels like luxury.",
  "I was ready to head home, but you just gave me a reason to stay.",
  "Are you a harmony? Because you make everything around you sound better.",
  "If someone told me perfection existed, I would’ve shown them you.",
  "You bring a whole new meaning to the word captivating.",
  "Are you a gentle breeze? Because you just swept me off my feet.",
  "I’m not trying to rush, but I definitely want you in my tomorrow.",
  "Are you a crescendo? Because every second near you gets more intense.",
  "If looking good was an Olympic event, you'd take home the gold with ease.",
  "You don't just command attention; you earn it with every look.",
  "Are you honey? Because sweetness follows you wherever you go.",
  "I’d love to tell you a secret, but I need your ear a little closer.",
  "Are you a lantern? Because you light up every dark corner in here.",
  "You're the kind of trouble anyone would gladly sign up for.",
  "Are you an anchor? Because with you, my heart finally feels settled.",
  "If life gave awards for best smiles, yours would sweep the ceremony.",
  "I came here expecting ordinary, but you turned it into unforgettable.",
  "Are you starlight? Because even in the dark, you make everything clear.",
  "I'd gladly lose a thousand arguments just to see you laugh like that.",
  "You're not just a chapter in a story; you're the whole book.",
  "Are you an overture? Because you're the start of something incredible.",
  "If charm had a masterclass, you'd be teaching the professors.",
  "I’m not looking for an adventure, but you look like a journey worth taking.",
  "Are you a classic? Because trends fade, but you are timeless.",
  "You're the reason I'm smiling at my shoes right now.",
  "If attraction was measurable, you'd break every dial in the building.",
  "Are you midnight? Because you're bold, beautiful, and impossible to ignore.",
  "I didn't know someone could look both dangerous and delightful at once.",
  "You're the plot twist I was hoping for all night.",
  "Are you a diamond in the rough? No, you're the polished crown jewel.",
  "I was going to say hello earlier, but I had to pick my jaw up first.",
  "If I could bottle your laugh, it would cure all my bad days.",
  "You don't just light up a room; you set the whole atmosphere on fire.",
  "Are you destiny? Because running into you feels completely meant to be.",
  "I’m not a fan of small talk, so let’s skip to when I can see you again.",
  "You carry a spark that could ignite the coldest winter night.",
  "Are you a signature? Because you leave an impression wherever you go.",
  "If I had one chance to make you smile, I’d take it every single time.",
  "You make the rest of the world look like it's in black and white."
];

smoothLines.forEach(text => add('smooth', text));

// -------------------------------------------------------------
// CHEESY (210 lines) - Classic punchlines, funny setups, puns
// -------------------------------------------------------------
const cheesyLines = [
  "Are you a parking ticket? Because you've got 'FINE' written all over you.",
  "Are you a campfire? Because you're hot and I want s'more.",
  "Do you have a map? I keep getting lost in your eyes.",
  "Are you French? Because Eiffel for you.",
  "Is your name Google? Because you have everything I've been searching for.",
  "Are you a time traveler? Because I see you in my future.",
  "Did the sun come out, or did you just smile at me?",
  "Feel my shirt. Know what it's made of? Boyfriend material.",
  "Your lips look lonely. Would they like to meet mine?",
  "Is your body from McDonald's? Because I'm lovin' it.",
  "Do you have a name or can I call you mine?",
  "Are you a beaver? Because daaaaam.",
  "Do you like raisins? How about a date?",
  "Are you a broom? Because you just swept me off my feet.",
  "Is your dad a baker? Because you've got the sweetest buns in town.",
  "Do you believe in love at first sight, or should I walk past again?",
  "Are you an interior decorator? Because when you walked in, the room was beautiful.",
  "Are you a magician? Because whenever I look at you, everyone else disappears.",
  "Are you religious? Because you're the answer to all my prayers.",
  "Did you hurt when you fell from heaven?",
  "Are you an alien? Because you just abducted my heart.",
  "Do you have an eraser? Because I can’t get you out of my mind.",
  "Is your dad an art thief? Because you look like a stolen masterpiece.",
  "Are you a bank? Because my interest in you keeps growing.",
  "If you were a chicken, you’d be im-peck-able.",
  "Are you a fruit? Because we’d make a great pear.",
  "Is your name Chapstick? Because you're da-balm.",
  "Are you a thief? Because you just stole my heart.",
  "Do you know CPR? Because you take my breath away.",
  "Are you a light switch? Because you turn me on.",
  "If you were a triangle, you'd be an acute one.",
  "Are you tired? Because you've been running through my thoughts all day.",
  "Are you a volcano? Because I lava you so much.",
  "Is your name Waldo? Because someone like you is hard to find.",
  "Are you Australian? Because you meet all of my koala-fications.",
  "Do you have a band-aid? Because I scraped my knee falling for you.",
  "Are you a dictionary? Because you add meaning to my life.",
  "Is your name Ariel? Because we mermaid for each other.",
  "Are you a snowstorm? Because you just made my heart race 40 miles an hour.",
  "If you were a transformer, you'd be Optimus Fine.",
  "Are you a carbon sample? Because I want to date you.",
  "Did you invent airplanes? Because you seem Wright for me.",
  "Are you a keyboard? Because you're just my type.",
  "Is your dad a boxer? Because you're a total knockout.",
  "Do you have a quarter? Because I want to call my mom and tell her I met the one.",
  "Are you an elevator? Because you lift my spirits up.",
  "Are you a camera lens? Because every time I see you, I focus.",
  "Is your name Summer? Because you're hot as July.",
  "Are you a teddy bear? Because I just want to hold you all night.",
  "If you were a star, you'd be the brightest one in the sky.",
  "Are you a soccer ball? Because I'm kicking myself for not talking to you sooner.",
  "Is your name Daisy? Because I have a planting urge to see you again.",
  "Are you a painter? Because you color my world.",
  "Do you have 11 protons? Because you are sodium fine.",
  "Are you a bowling ball? Because you knocked all my pins down.",
  "Is your name Honey? Because you're so sweet it's sticky.",
  "Are you a puzzle? Because I've been searching for your missing piece.",
  "If you were a burger, you'd be the McGorgeous.",
  "Are you a campfire marshmallow? Because you're golden brown and irresistible.",
  "Did you swallow magnets? Because I am undeniably drawn to you.",
  "Are you a library book? Because I'm totally checking you out.",
  "Is your name Cinderella? Because your beauty has no midnight curfew.",
  "Are you a cat? Because you're purr-fect in every way.",
  "Do you have a compass? Because I’m lost in your smile.",
  "Are you a lighthouse? Because you guide me straight through the dark.",
  "Is your name Autumn? Because I'm falling for you.",
  "Are you a pair of sunglasses? Because you make everything look brighter.",
  "If you were a dessert, you'd be a hot fudge sundae with extra cherries.",
  "Are you a diamond ring? Because you look like a lifetime commitment.",
  "Is your name Wi-Fi? Because I'm feeling a really strong connection.",
  "Are you a four-leaf clover? Because I'm lucky I stumbled onto you.",
  "Do you work at Starbucks? Because I like you a latte.",
  "Are you a candle? Because you brighten up any dinner table.",
  "Is your name Sunny? Because you radiate warmth wherever you step.",
  "Are you a pilot? Because you just sent my heart into cloud nine.",
  "If you were a shoe, you'd be a high heel because you elevate everything.",
  "Are you a smoothie? Because you're berry special.",
  "Is your dad an electrician? Because you're lighting up this entire room.",
  "Are you a cupcake? Because you're sweet and frosted to perfection.",
  "Do you have a mirror in your pocket? Because I see myself in your future.",
  "Are you a melody? Because you're stuck on repeat in my mind.",
  "Is your name Sugar? Because you make life so much sweeter.",
  "Are you an anchor? Because you keep me grounded.",
  "If you were a cookie, you'd be fresh out of the oven.",
  "Are you a superhero? Because you just saved my boring Friday night.",
  "Is your name Pepper? Because you add so much spice to the room.",
  "Are you an apple? Because you're the apple of my eye.",
  "Do you have a license? Because you're driving me crazy.",
  "Are you a sunflower? Because you always look toward the bright side.",
  "Is your name Rose? Because you're thorny with charm and lovely to behold.",
  "Are you a diamond? Because you're under pressure and still shining.",
  "If you were a vegetable, you'd be a cutecumber with style.",
  "Are you a blanket? Because being near you feels so cozy.",
  "Is your name Penny? Because you're worth so much more than people know.",
  "Are you a cloud? Because you float gracefully wherever you go.",
  "Do you have a watch? Because every second away from you drags on.",
  "Are you a rainbow? Because you bring color after every storm.",
  "Is your name Hope? Because you're exactly what I was wishing for.",
  "Are you a cupcake with sprinkles? Because you add joy to everything.",
  "If you were a flower, bees would follow you everywhere.",
  "Are you a teddy bear? Because hugging you would solve all my problems.",
  "Is your name Lucky? Because finding you felt like winning the lottery.",
  "Are you a warm cup of cocoa? Because you warm my heart right up.",
  "Do you have a guitar? Because you're pulling all my heartstrings.",
  "Are you a bookmark? Because you mark the best chapter of my day.",
  "Is your name Star? Because you guide my night sky.",
  "Are you a donut? Because I find you a-dough-rable.",
  "If you were a pen, you'd be a highlighter because you make everything pop.",
  "Are you a butterfly? Because you give me butterflies in my stomach.",
  "Is your name Joy? Because you bring a smile everywhere you go.",
  "Are you a cozy hoodie? Because I never want to let you go.",
  "Do you have a ticket? Because you've booked a permanent trip to my thoughts.",
  "Are you a campfire story? Because you keep me on the edge of my seat.",
  "Is your name Grace? Because you walk with so much elegance.",
  "Are you a milkshake? Because you bring all my attention right to you.",
  "If you were an emotion, you'd be happiness on a sunny Sunday.",
  "Are you a gold medal? Because you're the champion of my heart.",
  "Is your name Angel? Because heaven must be missing someone special.",
  "Are you a breeze on a hot day? Because you're refreshingly welcome.",
  "Do you have a flashlight? Because you light up my darkest paths.",
  "Are you a music box? Because you play the sweetest tunes in my mind.",
  "Is your name Valentine? Because you make every day feel like February 14th.",
  "Are you a jar of jam? Because you're sweet and spread joy everywhere.",
  "If you were a season, you'd be spring because you make everything bloom.",
  "Are you a snow angel? Because you're pure and cold-defyingly cute.",
  "Is your name Melody? Because your voice is pure music.",
  "Are you a shooting star? Because I'm making a wish on you right now.",
  "Do you have a puzzle piece? Because you fit right into my world.",
  "Are you a warm sweater? Because you make the chill disappear.",
  "Is your name Honeybee? Because you make the sweetest nectar.",
  "Are you a secret recipe? Because you've got all the best ingredients.",
  "If you were a color, you'd be rose gold because you shine so uniquely.",
  "Are you a warm bath? Because you take away all my stress.",
  "Is your name Belle? Because you're the beauty in my story.",
  "Are you a compass? Because you lead me in the right direction.",
  "Do you have an extra smile? Because mine got lost when I saw yours.",
  "Are you a constellation? Because you make the night look gorgeous.",
  "Is your name Sunshine? Because you brighten up every cloudy day.",
  "Are you a fresh bouquet? Because you smell like summer happiness.",
  "If you were a fruit tree, you'd be bearing sweetest peaches.",
  "Are you a cozy fire? Because you keep the cold far away.",
  "Is your name Dream? Because I don't ever want to wake up.",
  "Are you a pair of skates? Because you make my heart glide across the ice.",
  "Do you have a ribbon? Because you're tied to all my good thoughts.",
  "Are you a lullaby? Because you bring calm to my busy mind.",
  "Is your name Jewel? Because you're precious and rare.",
  "Are you a warm blanket on a rainy afternoon? Because you're all I need.",
  "If you were a melody, you'd be a timeless number-one hit.",
  "Are you a mirror? Because every time I look, I see perfection.",
  "Is your name Miracle? Because meeting you feels completely divine.",
  "Are you a clover? Because I'm feeling extra lucky today.",
  "Do you have a guitar pick? Because you've strummed my heart into rhythm.",
  "Are you an open book? Because I want to read every single line.",
  "Is your name Serenade? Because your presence sings to my soul.",
  "Are you a sunny day at the beach? Because you're golden and refreshing.",
  "If you were a sweet treat, you'd be a warm chocolate chip cookie.",
  "Are you a lighthouse beacon? Because you cut through all my foggy thoughts.",
  "Is your name Bliss? Because being near you is pure happiness.",
  "Are you a golden hour? Because everything looks breathtaking around you.",
  "Do you have a stamp? Because I want to mail you straight to my heart.",
  "Are you a treasure map? Because X definitely marks you.",
  "Is your name Wonder? Because you leave me amazed every time.",
  "Are you a cool sip of water? Because you quench my thirsty soul.",
  "If you were a garden, you'd be overflowing with blooming roses.",
  "Are you a heartbeat? Because without you, I wouldn't feel alive.",
  "Is your name Cherish? Because that's what I want to do with you.",
  "Are you a bright star? Because you stand out in the deepest night.",
  "Do you have a calendar? Because every day with you is a holiday.",
  "Are you a sweet whisper? Because you send shivers down my spine.",
  "Is your name Harmony? Because you blend perfectly with my life.",
  "Are you a warm sunset? Because you're the best ending to any day.",
  "If you were a dessert, you'd be crème brûlée: sweet with a little snap.",
  "Are you a cozy cabin in the woods? Because you feel like a sanctuary.",
  "Is your name Radiant? Because that's the only word that fits you.",
  "Are you a shooting star in August? Because you're rare and mesmerizing.",
  "Do you have a pocket watch? Because time stops whenever you smile.",
  "Are you a silver lining? Because you turn any bad day completely around.",
  "Is your name Symphony? Because you're an arrangement of perfection.",
  "Are you a fresh breeze in spring? Because you bring everything back to life.",
  "If you were a dance, you'd be a slow waltz under chandeliers.",
  "Are you a cup of tea? Because you soothe everything that hurts.",
  "Is your name Charm? Because you've cast a spell on me.",
  "Are you a fireworks display? Because you burst with brilliant colors.",
  "Do you have a bell? Because you ring true in every way.",
  "Are you an anchor in a storm? Because you keep my boat steady.",
  "Is your name Velvet? Because you're smooth and luxurious.",
  "Are you a sunrise over the mountains? Because you take my breath away.",
  "If you were a song, you'd be the encore everyone screams for.",
  "Are you a warm scarf? Because you wrap my heart in comfort.",
  "Is your name Spark? Because you lit a whole fire in my chest.",
  "Are you a gentle wave? Because you wash away all my worries.",
  "Do you have a passport? Because you've traveled right into my soul.",
  "Are you a constellation guide? Because you lead me through the dark.",
  "Is your name Treasure? Because you're the find of a lifetime.",
  "Are you a cup of hot cider? Because you warm me from the inside out.",
  "If you were a work of art, you'd be in the Louvre under glass.",
  "Are you a morning coffee? Because you're the first thing I crave.",
  "Is your name Promise? Because you make the future look bright.",
  "Are you a field of wildflowers? Because you're naturally stunning.",
  "Do you have a secret? Because your smile says you know something sweet.",
  "Are you a star in Orion? Because you shine with unmatched brilliance.",
  "Is your name Delight? Because you bring pure pleasure to my day.",
  "Are you a warm embrace? Because you make the whole world feel safe.",
  "If you were a dessert tray, you'd be the centerpiece everyone eyes.",
  "Are you a melody in D-major? Because you sound so uplifting and bright."
];

cheesyLines.forEach(text => add('cheesy', text));

// -------------------------------------------------------------
// NERDY (210 lines) - Code, tech, science, math, gaming, logic
// -------------------------------------------------------------
const nerdyLines = [
  "Are you made of copper and tellurium? Because you're definitely Cu-Te.",
  "Are you an exception? Because I'd catch you every single time.",
  "You must be the square root of -1, because you can't be real.",
  "Are you a CSS file? Because you've got so much style.",
  "Is your name Wi-Fi? Because I'm feeling an unmistakable connection.",
  "Are you an algorithm? Because my heart rate increases logarithmically whenever you're around.",
  "If you were a function, you'd be recursive, because you keep running through my mind.",
  "Are you git commit -m 'Initial commit'? Because you are the start of something great.",
  "Are you an API with zero rate limits? Because I can’t stop sending requests to be around you.",
  "Are you root access? Because you just bypassed all my permissions.",
  "According to the second law of thermodynamics, you're supposed to share your heat with me.",
  "Are you a keyboard? Because you're definitely my type.",
  "Are you Bluetooth? Because I'm trying to pair up with you right now.",
  "Are you a quantum particle? Because whenever I observe you, my state changes.",
  "Is your name HTML? Because you give my life structure.",
  "Are you a breakpoint? Because you make my world pause.",
  "Are you a GPU? Because you're rendering my heart at 120 FPS.",
  "If you were a variable, you'd be a constant, because you never change my admiration.",
  "Are you an SSD? Because you speed up all my processes.",
  "Is your IP address 127.0.0.1? Because there's no place like home with you.",
  "Are you a pull request? Because I want to merge our branches together.",
  "Are you an infinite loop? Because I never want to break out of you.",
  "Is your name Linux? Because you have complete control over my kernel.",
  "Are you a carbon nanotube? Because your strength and beauty are nanoscale perfection.",
  "Are you a neutrino? Because you pass right through my defenses without resistance.",
  "If you were an element, you'd be Francium, because you're the most attractive on the table.",
  "Are you Dijkstra's algorithm? Because you found the shortest path straight to my heart.",
  "Are you an IDE? Because you auto-complete my thoughts.",
  "Are you a syntax error? Because everything stops when you show up.",
  "Is your love an open port? Because I'd love to establish a handshake.",
  "Are you a stack overflow? Because my feelings for you can't be contained in memory.",
  "Are you dark matter? Because you're invisible to the eyes, but your gravity holds me together.",
  "Is your name Java? Because you give me object-oriented affection.",
  "Are you a semiconductor? Because you're conducting all my electrical impulses.",
  "Are you a logic gate? Because you're the 'AND' to all my conditions.",
  "If I were an enzyme, I'd be DNA helicase so I could unzip your genes.",
  "Are you a binary star? Because we are orbiting each other in gravitational harmony.",
  "Is your name Python? Because being around you is so clean and readable.",
  "Are you a cache? Because you save my favorite memories for instant retrieval.",
  "Are you an electron? Because I'm feeling a strong positive charge when you're near.",
  "Are you an event listener? Because you react to every touch.",
  "If you were a game console, you'd be next-gen because you're leagues ahead of the rest.",
  "Are you a hypervisor? Because you're managing all my virtual emotions.",
  "Is your name TypeScript? Because you bring type safety to my chaotic life.",
  "Are you a laser? Because you're focused, monochromatic, and totally captivating.",
  "Are you a black hole? Because your event horizon pulls me in with no escape.",
  "If you were an angle, you'd be 90 degrees because you are looking just right.",
  "Are you a distributed system? Because your presence scales across my entire mind.",
  "Are you machine learning? Because with every interaction, my affection for you improves.",
  "Is your heartbeat a clock cycle? Because it synchronizes my entire world.",
  "Are you a database index? Because you cut my query time to zero.",
  "Are you an optical fiber? Because you transmit joy at the speed of light.",
  "If you were an asteroid, you'd make an impact crater on my heart.",
  "Are you a responsive design? Because you look stunning across every screen.",
  "Is your name Boolean? Because you're true in every single way.",
  "Are you a supercollider? Because colliding with you created pure energy.",
  "Are you an SSD cache? Because you make all my cold boots warm instantly.",
  "If you were a query, you'd be SELECT * FROM heaven WHERE angel = true.",
  "Are you a terminal command? Because you just executed an override on my pulse.",
  "Are you a gravitational wave? Because your ripple just distorted spacetime around me.",
  "Is your name Docker? Because you've containerized all my happiness in one spot.",
  "Are you an opcode? Because you instruct my heart to skip a beat.",
  "Are you an exothermic reaction? Because you're giving off incredible heat.",
  "If you were a neural net, you'd have zero loss and 100% accuracy.",
  "Are you an SSL certificate? Because you make me feel verified and secure.",
  "Are you a magnetic field? Because you align all my wandering electrons.",
  "Is your name Vim? Because once I enter your world, I never want to leave.",
  "Are you an overclocked CPU? Because you're running dangerously hot.",
  "Are you a high-refresh monitor? Because watching you is buttery smooth.",
  "If you were a celestial body, you'd be a pulsar, beaming rhythmically into my soul.",
  "Are you a hotkey shortcut? Because you save me time and make everything effortless.",
  "Are you a microchip? Because you power my entire thinking process.",
  "Is your name React? Because every time you change, my whole state re-renders.",
  "Are you a telescope? Because you bring the distant stars right into focus.",
  "Are you a solar panel? Because you convert my sunny days into pure power.",
  "If you were an algorithm, you'd be O(1) because you're constant perfection.",
  "Are you a superconductor? Because with zero resistance, I fell for you immediately.",
  "Are you an encryption key? Because only you can unlock my private thoughts.",
  "Is your name CSS Flexbox? Because you align all my elements without hassle.",
  "Are you an Aurora Borealis? Because your geomagnetic glow is hypnotic.",
  "Are you a git rebase? Because you gave my history a whole clean trajectory.",
  "If you were a planet, you'd be Venus because you outshine the morning sky.",
  "Are you a heat sink? Because you absorb all my daily stress.",
  "Are you a clean commit message? Because you describe exactly what I'm looking for.",
  "Is your name Fibonacci? Because the more I look at you, the more divine the ratio.",
  "Are you an optical illusion? Because you look too good to be physically possible.",
  "Are you a patch update? Because you resolved every bug in my routine.",
  "If you were an orbital trajectory, you'd be geosynchronous, staying right above me.",
  "Are you a motherboard? Because you connect all my essential parts.",
  "Are you a compiler? Because you turn all my messy code into working poetry.",
  "Is your name HTTP 200? Because everything about you is OK.",
  "Are you a satellite dish? Because you receive all my signals loud and clear.",
  "Are you an atomic clock? Because you measure time with absolute precision.",
  "If you were a data structure, you'd be a graph because our connections are endless.",
  "Are you a renewable energy source? Because you keep giving without running dry.",
  "Are you a prism of light? Because you separate my ordinary into a rainbow.",
  "Is your name Rust? Because you prevent all my memory leaks.",
  "Are you an orbital resonance? Because our timing is mathematically locked.",
  "Are you a sound card? Because your voice sounds like high-fidelity audio.",
  "If you were a math problem, you'd be an identity because you balance everything.",
  "Are you a web crawler? Because you indexed every corner of my heart.",
  "Are you a mechanical switch? Because your tactile feedback is so satisfying.",
  "Is your name SQL? Because you query my deepest affections.",
  "Are you a cloud server? Because you elevate my thoughts into the stratosphere.",
  "Are you an ambient sensor? Because you adapt to every environment effortlessly.",
  "If you were a star system, you'd be Alpha Centauri: closest and brightest.",
  "Are you a low-latency pipeline? Because you deliver smiles in microseconds.",
  "Are you an electric dipole? Because you induce an irresistible polarity in me.",
  "Is your name Tailwind? Because you style my life with zero effort.",
  "Are you a space shuttle? Because your launch took my breath away.",
  "Are you a quantum superposition? Because you're everywhere I look at once.",
  "If you were a keyboard layout, you'd be Ergonomic because you feel so natural.",
  "Are you a clean pull request? Because I approve you without any review comments.",
  "Are you an infrared camera? Because you can see the warmth rising off my cheeks.",
  "Is your name Swift? Because being with you is fast and modern.",
  "Are you a gyro sensor? Because you keep my orientation balanced.",
  "Are you an ultra-wide monitor? Because my vision is completely filled by you.",
  "If you were a chemistry experiment, you'd be a precipitate because you settled in my heart.",
  "Are you a microkernel? Because you handle only the purest essentials.",
  "Are you a fiber-optic cable? Because light bends just to follow your path.",
  "Is your name NodeJS? Because you handle all my asynchronous requests with ease.",
  "Are you an exoplanet in the habitable zone? Because life thrives near you.",
  "Are you a clean git tag? Because you mark a milestone in my year.",
  "If you were a math theorem, you'd be Fermat's Last: famously captivating.",
  "Are you a solid-state battery? Because you carry immense energy safely.",
  "Are you an OLED screen? Because your blacks are deep and your colors are vibrant.",
  "Is your name Golang? Because you handle concurrency like a champ.",
  "Are you a magnetic levitation train? Because you glide without friction.",
  "Are you a diffraction grating? Because you break through all monochromatic boredom.",
  "If you were a code snippet, you'd be a one-liner that solves world hunger.",
  "Are you an astronomical twilight? Because your soft glow is magical.",
  "Are you a high-gain antenna? Because you amplify my best signals.",
  "Is your name NextJS? Because you pre-render all my sweetest hopes.",
  "Are you a planetary nebula? Because you are cosmic beauty born from fire.",
  "Are you a heatsink fan? Because you keep me cool when things get intense.",
  "If you were a physics constant, you'd be the speed of light: the ultimate ceiling.",
  "Are you an automated workflow? Because you streamline all my happiness.",
  "Are you a piezoelectric crystal? Because applying pressure to you generates electricity.",
  "Is your name Git? Because you track every change in my heartbeat.",
  "Are you an orbital re-entry? Because you're entering my atmosphere with serious heat.",
  "Are you an encrypted tunnel? Because between us, everything stays safe.",
  "If you were a logic statement, you'd be tautology: always true.",
  "Are you a stellar eclipse? Because you make everything else take a backseat.",
  "Are you an inductive coil? Because you transfer energy without even touching.",
  "Is your name C++? Because you give me high-performance emotion.",
  "Are you a radar system? Because you detected my affection from miles away.",
  "Are you a deep learning model? Because you generalize my joy across every day.",
  "If you were a planetary ring, you'd be Saturn's: majestic and iconic.",
  "Are you a thermal paste? Because you make the connection between us conduct perfectly.",
  "Are you an API gateway? Because you route all my best thoughts to one destination.",
  "Is your name GraphQL? Because you give me exactly what I request and nothing less.",
  "Are you a supernova remnant? Because you enrich my whole universe with gold.",
  "Are you an optical sensor? Because you capture every fine detail of my mood.",
  "If you were an operating system, you'd have 99.999% uptime in my thoughts.",
  "Are you a solar wind? Because you trigger an aurora across my whole sky.",
  "Are you an analog synth? Because your warmth is unmistakable.",
  "Is your name JSON? Because you format my messy world into clean keys and values.",
  "Are you an aerodynamic wing? Because being with you generates pure lift.",
  "Are you a laser diode? Because your focus cuts through any fog.",
  "If you were a celestial alignment, you'd be a solstice: bright and unforgettable.",
  "Are you a fast Fourier transform? Because you decompose all my complex frequencies into harmony.",
  "Are you an active cooler? Because you keep my system stable when you're around.",
  "Is your name SSH? Because our connection is direct, private, and encrypted.",
  "Are you a radio telescope? Because you pick up the faintest whispers of beauty.",
  "Are you a parallel processor? Because you're on my mind while I do ten other things.",
  "If you were an orbital period, you'd be 365 days of constant sunshine.",
  "Are you a clean commit hook? Because you reject anything that isn't genuine.",
  "Are you an electric motor? Because you produce instant torque in my chest.",
  "Is your name Linux Mint? Because you are refreshingly smooth.",
  "Are you a space-time geodesic? Because following you is the natural path of gravity.",
  "Are you a high-density cluster? Because your processing power leaves me amazed.",
  "If you were a circuit diagram, you'd be a closed loop of pure power.",
  "Are you a dark mode toggle? Because you're so easy on my eyes.",
  "Are you a satellite uplink? Because talking to you connects me to the whole world.",
  "Is your name Markdown? Because you make simple text look incredible.",
  "Are you an astronomical observatory? Because you sit above the clouds looking at wonders.",
  "Are you an induction charger? Because just lying next to you fills my battery.",
  "If you were a gaming rig, you'd be liquid-cooled with zero stutter.",
  "Are you a quantum entanglement? Because distance doesn't change how connected we are.",
  "Are you a zero-day exploit? Because you penetrated all my security with zero warning.",
  "Is your name Open Source? Because you share your goodness with the whole world.",
  "Are you an electromagnetic pulse? Because you temporarily disabled all my logic.",
  "Are you an ultra-low latency server? Because your reply arrived before I finished asking.",
  "If you were a space probe, you'd be Voyager: heading into endless beauty.",
  "Are you an audio interface? Because you bring out the best tone in my voice.",
  "Are you a clean git branch? Because merging with you has zero conflicts.",
  "Is your name Arch? Because you're built exactly the way you want to be.",
  "Are you a gravitational lens? Because you magnify everything wonderful behind you.",
  "Are you a high-res DAC? Because you decode all my feelings into crisp sound.",
  "If you were a science theorem, you'd be universally accepted.",
  "Are you a biometric lock? Because you respond only to my touch.",
  "Are you an optical prism? Because white light turns into magic when you pass through.",
  "Is your name Vite? Because you boot up my excitement with zero wait time.",
  "Are you a cosmic ray? Because you sparked an idea the second you entered my atmosphere.",
  "Are you an uninterruptible power supply? Because you keep me going when everything else fails.",
  "Are you a thermal imaging camera? Because you can see how hot you make me feel.",
  "Are you an overclock button? Because my pulse doubled the moment you looked at me.",
  "Is your name GitHub? Because I want to fork your attention and submit my best work.",
  "Are you a lossless compression format? Because everything about you is pure fidelity.",
  "Are you an electron microscope? Because you reveal all the hidden details I love.",
  "Are you a multi-core processor? Because you handle all my thoughts simultaneously.",
  "Are you a high-voltage transformer? Because you step up my energy instantly.",
  "Is your name Linux Kernel? Because you are the core of all my stability.",
  "Are you a zero-latency protocol? Because talking to you happens without any delay.",
  "Are you an OLED panel? Because your contrast is unmatched and you shine so bright.",
  "Are you a variable in global scope? Because you are accessible from anywhere in my heart."
];

nerdyLines.forEach(text => add('nerdy', text));

// -------------------------------------------------------------
// ROMANTIC (210 lines) - Sweet, sincere, deep, poetic, warm
// -------------------------------------------------------------
const romanticLines = [
  "I was having a completely average week until you walked in and ruined my concentration.",
  "You have no idea how hard it was to pretend I wasn't checking you out just now.",
  "I'm not usually someone who interrupts, but walking past you felt like a mistake I'd regret all night.",
  "I didn't really know what my type was until about thirty seconds ago.",
  "You look like someone who could ruin my sleep schedule, and honestly, I'm completely fine with it.",
  "Are you free for the rest of your life? Because I could definitely get used to that smile.",
  "I told myself I was staying in tonight, but now I'm thanking whatever convinced me to come out.",
  "You have that rare kind of beauty where everything else in the room just goes out of focus.",
  "I don't know what your plans are for tonight, but I really hope they end with me getting your number.",
  "I’m not a gambler, but I’d put all my money on you being the most captivating person in this city.",
  "If I could rearrange my week, I’d put every single evening next to you.",
  "I wasn’t looking for trouble tonight, but you’re definitely the kind of trouble worth getting into.",
  "You have a smile that could turn an awful Monday into the best day of the year.",
  "I could listen to you talk about literally anything just to watch the way your eyes light up.",
  "I was going to play it cool, but honestly, you're entirely too attractive for me to pretend.",
  "You make confidence look easy, and being completely irresistible look effortless.",
  "I never believed in love at first glance, but you just made me a very fast believer.",
  "There are eight billion people on this planet, but right now you're the only one I see.",
  "Can I take you out sometime, or should I just keep admiring you from three feet away?",
  "I don't know what perfume you're wearing, but it just became my absolute favorite scent.",
  "You look like the kind of person who deserves to be spoiled and never taken for granted.",
  "I can't tell if that smile was meant for me, but my heart definitely took it personally.",
  "I’m not trying to rush into anything, but I already know you’re going to be impossible to forget.",
  "Every time you look over here, I completely forget what I was about to say.",
  "You have that kind of warmth that makes anyone want to stay a little longer.",
  "I'd cross this room a hundred times just for another excuse to hear your voice.",
  "You're the first person I've met who looks even better in real life than anyone could imagine.",
  "I'm usually pretty good at keeping my composure, but you're making it ridiculously hard.",
  "If this was a movie, this would be the exact scene where the main character realizes they're in big trouble.",
  "You have the kind of energy that makes everything else feel exciting.",
  "I think the universe owes me a thank-you for finally working up the courage to say hi.",
  "You are effortlessly the best part of my entire evening.",
  "I don't usually initiate conversations like this, but walking away without your name would haunt me.",
  "You've got that dangerous combination of being smart, witty, and completely unforgettable.",
  "I was told good things come to those who wait, but seeing you made me lose all patience.",
  "You have the kind of eyes that make people want to tell you their whole life story.",
  "I don't know what you did to this room, but it got a lot brighter the second you stepped inside.",
  "I'd love to take you out for dinner, or we can just skip straight to desert and talk until midnight.",
  "You have a presence that commands the whole room without even trying.",
  "I didn't think anyone actually looked that good in candid lighting.",
  "If being effortlessly charming was a crime, you'd be serving a life sentence.",
  "I'm not saying you're my soulmate, but the universe definitely wants us talking right now.",
  "I was ready to leave twenty minutes ago, and then you showed up and changed everything.",
  "You look like every great daydream I've ever had wrapped into one person.",
  "Can you look at me like that again? My heart didn't catch it the first time.",
  "You have an elegance that makes modern dating feel like a classic romance.",
  "I'm completely helpless against that laugh of yours.",
  "I'd trade every boring weekend I've ever had for one quiet evening with you.",
  "You make making eye contact feel like a high-stakes sport.",
  "I hope you're having an amazing night, but I'd love to make it even better.",
  "You have that kind of smile that could disarm an entire army.",
  "I wasn't planning on meeting anyone special tonight, so thanks for ruining my schedule.",
  "You make ordinary conversation feel like a spark waiting to catch fire.",
  "I'd never play games with someone whose attention is this valuable.",
  "You have a way of looking at someone that makes them feel like the only person in the room.",
  "I want to know what makes you laugh like that when nobody's watching.",
  "Meeting you feels like finding an oasis in the middle of a loud desert.",
  "I don't need a hundred reasons to like you; that look you just gave me is more than enough.",
  "You're the kind of person someone writes late-night songs about.",
  "I'm not usually one to stare, but you're giving me no other choice.",
  "Every second spent talking to you feels like a second well spent.",
  "You have the kind of beauty that stays on someone's mind for days after.",
  "I was having a rough day until you smiled at me, and suddenly everything reset.",
  "You're not just a catch; you're the whole ocean.",
  "I'd love to learn everything that makes you tick, starting tonight.",
  "You make taking a chance on someone feel completely worth the risk.",
  "I don't know what tomorrow holds, but I know I want you in it.",
  "You have that natural glow that no filter or lighting could ever replicate.",
  "I could get lost in a conversation with you and not care about what time it is.",
  "You make heartbeats feel like drum solos.",
  "I'm ready to swear you were customized specifically to my taste.",
  "You carry yourself with a grace that demands respect and a smile that invites love.",
  "I'd wait in line for hours just to get two minutes of your undivided attention.",
  "You have the kind of eyes that make secrets impossible to keep.",
  "I didn't know someone could look so sophisticated and so approachable all at once.",
  "If I could save one glance from tonight, it would be the one you just gave me.",
  "You make this whole room look like background scenery.",
  "I don't need luck when I've got the courage to stand in front of someone like you.",
  "You're the plot twist I was hoping for all year.",
  "I'd love to be the reason behind that smile tomorrow morning.",
  "You have a laugh that sounds like my favorite song on vinyl.",
  "I wasn't looking for someone to sweep me off my feet, but you're doing a fantastic job.",
  "You are proof that real elegance never goes out of style.",
  "I want to know the story behind every little smile you try to hold back.",
  "You make romance feel like an adventure instead of a cliché.",
  "I'd give you the world if I could, but let's start with a really good coffee date.",
  "You have a warmth that makes people feel safe and excited at the same time.",
  "I'm not usually this bold, but staying silent around you felt like a tragedy.",
  "You look like the kind of memory I’d replay on loop.",
  "I didn't know perfection existed in three dimensions until you walked past.",
  "You have a way of speaking that makes every word sound important.",
  "I want to be the one you text when something crazy happens in your day.",
  "You make chemistry feel like an understatement.",
  "I'd travel halfway around the world just to sit across from you at dinner.",
  "You're the kind of person who makes leaving early impossible.",
  "I can't tell what's more dangerous: your smile or the way you look at me.",
  "You have that rare magnetism where people can't help but lean in closer.",
  "I don't want a superficial connection; I want to know who you really are.",
  "You make falling for someone look like the easiest decision on earth.",
  "I’m ready to bet that getting to know you is the best decision I'll make this month.",
  "You have that quiet confidence that speaks louder than anyone in this room.",
  "I could spend a lifetime learning all your favorite things and never get bored.",
  "You make my pulse jump every time our eyes lock.",
  "I didn't realize how much I was hoping to run into someone like you until now.",
  "You have a gentle power that draws everyone into your orbit.",
  "I'd love to take you somewhere quiet where I can actually hear your thoughts.",
  "You're the kind of person who turns a casual evening into an unforgettable memory.",
  "I don't care where we go, as long as you're sitting in the passenger seat.",
  "You have a smile that could melt the most stubborn heart.",
  "I was thinking about leaving, but leaving without your number seems like a crime.",
  "You make modern romance feel authentic and effortless again.",
  "I'd happily listen to your playlist for hours just to know what you feel.",
  "You're the breath of fresh air this whole week needed.",
  "I can't imagine anyone being lucky enough to have your full attention and not appreciating it.",
  "You have that rare spark that turns curiosity into obsession.",
  "I want to make you smile the way you just made me smile.",
  "You make taking risks feel like the only reasonable option.",
  "I don't know what's in your future, but I'd love to earn a spot in it.",
  "You have an undeniable gravity that pulled me straight across this room.",
  "I'd walk through pouring rain just to drop an umbrella off for you.",
  "You're the kind of person someone writes letters to instead of quick texts.",
  "I didn't know someone could look both fierce and incredibly sweet at the same time.",
  "You have a rhythm that my heartbeat wants to match.",
  "I want to know the thoughts you only share late at night.",
  "You make being in love look like the highest art form.",
  "I'd love to make you laugh until your cheeks hurt.",
  "You're the spark that turned a dark evening into pure gold.",
  "I don't need a thousand wishes; I just need one evening with you.",
  "You have that irresistible combination of vulnerability and strength.",
  "I can't look away from you without immediately wanting to look back.",
  "You make my world feel significantly bigger and softer.",
  "I'd love to be the reason you look forward to waking up tomorrow.",
  "You have the kind of eyes that see straight through any facade.",
  "I didn't know beauty could have this much depth.",
  "You make quiet moments feel richer than a crowded room.",
  "I'd choose five minutes of your real attention over a full day with anyone else.",
  "You're the secret I want to keep all to myself.",
  "I want to know your dreams, your fears, and what makes you smile when you're alone.",
  "You make being genuine look like the most attractive trait in the world.",
  "I'd cross oceans just to hear you say you missed me.",
  "You have that effortless glow that turns heads without making a sound.",
  "I can't tell if you're an answered prayer or the sweetest coincidence.",
  "You make patience feel impossible and anticipation feel wonderful.",
  "I'd love to hold your coat and walk you home under the streetlights.",
  "You're the reason I'm smiling at my screen right now.",
  "I didn't know what home felt like in human form until you stood next to me.",
  "You have a voice that could calm the roughest storm.",
  "I want to know every detail of what makes you who you are.",
  "You make courage feel like the only logical choice.",
  "I'd happily spend my entire weekend just listening to your stories.",
  "You're the kind of person who deserves flowers on a random Tuesday.",
  "I can't imagine my week getting any better than right now.",
  "You have that timeless charm that never fades.",
  "I want to be the one who makes you feel safe enough to be completely yourself.",
  "You make love feel like the most natural thing in the world.",
  "I'd choose your laugh over silence every single day.",
  "You're the sweetest disruption my life has had in a very long time.",
  "I didn't know someone's glance could carry so much weight.",
  "You have an aura that makes everything around you feel a little warmer.",
  "I'd love to see where this chemistry takes us if you're willing to find out.",
  "You're the best coincidence that has happened to me all year.",
  "I want to know what makes your heart race as fast as mine is racing right now.",
  "You make every romantic cliché feel like an absolute truth.",
  "I'd trade every late night out just to stay in and talk with you.",
  "You have that special something that makes you stand out from the crowd.",
  "I can't stop wondering what it feels like to hold your hand.",
  "You make honesty feel sexy and vulnerability feel brave.",
  "I want to be the favorite part of your day.",
  "You're the person I didn't know I was waiting for.",
  "I didn't think I had room for butterflies, but you proved me wrong in seconds.",
  "You have a way of looking at life that makes me want to see it through your eyes.",
  "I'd love to take care of you on your worst days and celebrate with you on your best.",
  "You're the sweetest surprise this evening had in store.",
  "I can't help but feel like we were meant to cross paths tonight.",
  "You have that rare grace that leaves an imprint long after you walk away.",
  "I want to be the one who makes your eyes sparkle like that.",
  "You make the future look like something truly worth looking forward to.",
  "I'd love to write our story together, one chapter at a time.",
  "You're the kind of beauty that words can never quite capture.",
  "I can't tell if you're an angel or just my favorite kind of daydream.",
  "You make my heart beat with a rhythm I haven't felt in forever.",
  "I want to know every silly thing that makes you happy.",
  "You're the missing note in the melody I've been humming all week.",
  "I didn't know I could feel this drawn to someone so quickly.",
  "You have a tenderness that makes the world feel a little less harsh.",
  "I'd love to be the reason you look in the mirror and know you're adored.",
  "You make intimacy feel effortless and connection feel magnetic.",
  "I want to give you reasons to smile every single day.",
  "You're the sunrise after a very long, dark night.",
  "I can't imagine anyone ever meeting you and forgetting who you are.",
  "You have that irresistible combination of poise and playfulness.",
  "I'd love to make memories with you that we both smile about years from now.",
  "You make falling in love feel like coming home.",
  "I want to learn the language of your smiles.",
  "You're the sweetest piece of luck I've had in ages.",
  "I didn't know one person could make an entire room feel electric.",
  "You have a heart that deserves to be treasured every single day.",
  "I'd love to be the one who gets to hold you when the night gets cold.",
  "You make every moment feel significant just by being in it.",
  "I want to walk with you through every chapter life has to offer.",
  "You're the kind of person who makes love songs feel personal.",
  "I didn't know my heart was looking for someone until it found you.",
  "You have that captivating light that never dims.",
  "I'd love to be the hand you reach for in a crowded room.",
  "You make devotion feel like the highest privilege on earth.",
  "I want to know the dreams you're afraid to say out loud.",
  "You're the sweetest thing that's crossed my path in forever.",
  "I can't wait to see where our story begins."
];

romanticLines.forEach(text => add('romantic', text));

// -------------------------------------------------------------
// FUNNY (210 lines) - Banter, self-aware jokes, situational humor
// -------------------------------------------------------------
const funnyLines = [
  "Not to be dramatic, but if we don’t get drinks, my therapist will be hearing about you for the next six months.",
  "I saw you from across the room and my last two brain cells had a heated argument about who was gonna come talk to you.",
  "I told my friends I was going to the bathroom, but I actually just walked in a circle to hype myself up to say hi.",
  "I don’t usually approach people, but my pride decided to take tonight off.",
  "Look, I’m not saying I’m the catch of your life, but I will never ask you 'where do you wanna eat?' and then reject five of your suggestions.",
  "I was going to wait for you to notice me, but I have a bedtime and rent to pay.",
  "I’m legally required to inform you that I have zero game, but I do have snacks in my car.",
  "Quick question: what’s our plan for when our eyes meet again? Because I panicked the first time.",
  "I’m not playing hard to get, I’m playing 'praying I don’t trip over my own feet on the way over to you.'",
  "I was gonna say something mysterious, but I choke on water while sitting still, so let's keep expectations realistic.",
  "On a scale of 1 to 'pretending to check my phone because you walked by', how obvious was I just now?",
  "I don't have a pickup line, I just have poor impulse control and you're very attractive.",
  "I just practiced saying 'hey' five times in my head and every single version sounded like a cartoon villain. So... hello.",
  "I'm willing to lie about how we met if you are.",
  "If you think I'm awkward right now, just wait until you see me trying to parallel park.",
  "I have no idea what I’m doing, but you looked like you were having too much fun and I’d like to ruin that with my company.",
  "Are we about to start an epic love story or are you about to tell me you have a boyfriend? Either way, let's rip the band-aid off.",
  "I promise I'm a lot more charming after the initial panic wears off.",
  "Can you pretend we're having an intense conversation so I look popular for three minutes?",
  "I'm only talking to you so I can brag to my group chat that I shot my shot with the prettiest person here.",
  "I gave up on being mysterious about three seconds after seeing your face.",
  "I just want you to know that if we end up dating, my mom is already going to like you more than me.",
  "My confidence peaked about forty seconds ago, so whatever comes out of my mouth right now is completely unedited.",
  "I’d ask for your number, but I feel like we should at least argue about something petty first.",
  "I’m not saying you’re intimidating, but my Apple Watch just congratulated me on completing a high-intensity workout.",
  "I was gonna play it cool, but then I remembered I have zero cool to play with.",
  "Look, I’m not a smooth talker. I’m just a person standing in front of a significantly more attractive person, hoping for the best.",
  "Can I buy you a drink, or would you prefer the cash equivalent to leave you alone?",
  "I looked at you and completely forgot what I was doing with my life.",
  "I know this is sudden, but my friends said I wouldn't do it, and I have ten dollars and my fragile ego on the line.",
  "I don't know what's harder: approaching you, or pretending I didn't just spend 10 minutes working up the courage.",
  "If you reject me right now, can you at least do it with a soft voice so I can save face in front of the bartender?",
  "I'm really good at three things: trivia, ordering takeout, and embarrassing myself in front of attractive people.",
  "You look like someone who has their life together, and I'd love to learn what that feels like.",
  "I was going to send you a drink from across the bar, but I didn't want to risk the waiter drinking it.",
  "I'm not trying to rush into anything, but what's our plan for when our families meet at Thanksgiving?",
  "I didn't prepare a backup plan in case you actually smiled back, so give me like five seconds to reboot.",
  "My friends told me to play it casual, so here I am, casually staring at you like a lost golden retriever.",
  "I have two left feet, a bad sense of direction, and an incredible desire to get to know you.",
  "I was going to ignore you to play hard to get, but honestly, I don't have the emotional discipline for that.",
  "I told my friend I was coming over here to ask for directions, but the only destination I care about is your contact list.",
  "I’m not saying you owe me a conversation, but I did just spend three minutes dodging two waiters to get over here.",
  "I'm about 70% water and 30% bad decisions, but I swear I have a good personality.",
  "If I say something dumb in the next thirty seconds, can we agree to blame it on the lighting?",
  "I was trying to come up with something witty, but you smiled and completely deleted my vocabulary.",
  "I'm fully aware you're out of my league, but I'm a big fan of underdog stories.",
  "Can you tell me your name so I know what to scream when I wake up from this dream?",
  "I’m terrible at small talk, so let's just debate something high stakes like whether pineapple belongs on pizza.",
  "I saw you walking this way and my survival instinct completely vanished.",
  "I'm not saying you're my soulmate, but I did just check my bank account to see if I can afford to impress you.",
  "My friends are watching from over there, so if this goes badly, can you at least laugh politely so they think I'm doing great?",
  "I’m usually much cooler on text, but I didn't want someone else to steal the chance to get rejected in person.",
  "I'd offer to carry your drink, but honestly, my hands are shaking enough to turn it into a cocktail shaker.",
  "I came over here with a plan, but your face made me forget every step of it.",
  "I'm not saying I'm a ten, but on a good day with low lighting and the right angle, I can definitely pass for a solid seven.",
  "I was going to play the mysterious stranger, but I sneezed twice on the walk over, so that ship has sailed.",
  "I hope you like uncoordinated dancing and overthinking every social interaction, because that's my entire portfolio.",
  "I looked up 'how to talk to beautiful people' on my phone, and it said 'good luck buddy.' So here I am.",
  "I have a strict policy against talking to strangers, but you look like someone worth breaking rules for.",
  "I’m not trying to be forward, but my dog saw your picture and said you look like a great listener.",
  "I had a whole speech prepared, but then you made eye contact and my brain pulled the fire alarm.",
  "I’m pretty sure our astrological signs are completely incompatible, which means the banter is going to be phenomenal.",
  "I don’t know what kind of trouble you usually get into, but I have a completely clear schedule.",
  "I was going to ask what your favorite book is, but let's be real, I'm just looking for an excuse to hear your voice.",
  "I'm willing to bet you five bucks that I can guess your coffee order on the third try.",
  "I didn't think anyone actually looked that good without three beauty filters and studio lighting.",
  "I’m standing here trying to act natural, but I think I just look like an undercover cop at a rave.",
  "I would ask you what you do for a living, but I’m more interested in what you do when you’re trying to avoid doing it.",
  "I’m not great at reading social cues, so feel free to tap me on the shoulder if I'm being too charming.",
  "I was going to buy you a drink, but my financial advisor said I should start with a sincere compliment first.",
  "I came over to ask for your opinion on a very serious debate: are hot dogs sandwiches?",
  "I’m not saying you're intimidating, but I definitely had to do a motivational montage in my head before walking over.",
  "I don't have a witty opening line, but I do have an uncanny ability to remember completely useless movie quotes.",
  "I saw you and immediately decided that whatever I was doing before was completely irrelevant.",
  "I’m not a professional psychic, but I see a lot of unread texts in our very near future.",
  "I was trying to look engaged in my drink, but it was just club soda and I was really just staring at you.",
  "I’m pretty sure my heart rate just exceeded the recommended daily limit for sitting down.",
  "I’m not saying you should give me your number, but it would save me from having to awkwardly wander back to my friends.",
  "I was hoping you'd look over and give me an easy opening, but you were too busy looking effortlessly cool.",
  "I’m really bad at poker because every time someone attractive walks by, my face tells the whole table.",
  "I was going to ask if you come here often, but I really don't want to sound like a character from an 80s sitcom.",
  "I don’t usually take risks on weeknights, but here I am, risking public humiliation for a shot at saying hi.",
  "I told myself I’d only stay for one drink, and then you showed up and ruined my eight hours of sleep.",
  "I’m not saying I’m the best conversationalist in this room, but I can definitely out-listen anyone here.",
  "I was going to play the strong, silent type, but silence gives me anxiety, so you get the talkative version.",
  "I came over here because my friends said you looked friendly, and I said 'no, they look dangerous in a fun way.'",
  "I’m not trying to rush the process, but I already know we're going to disagree on the temperature of the AC.",
  "I saw you from across the room and my brain immediately filed an emergency request for courage.",
  "I’m not saying you’re a problem, but you’re definitely the kind of problem my parents warned me about.",
  "I’d ask you to dance, but my doctor advised against subjecting the public to that kind of trauma.",
  "I was trying to figure out what you're thinking right now, and my best guess is: 'who is this clown?'",
  "I’m not usually impulsive, but walking past you without saying anything felt like a crime against my own future.",
  "I don’t know what kind of music you listen to, but I’m ready to nod along like I’ve been a fan for years.",
  "I was going to ask if you believe in love at first sight, but honestly, I'm just hoping you believe in second chances after awkward intros.",
  "I’m not saying I’m a great catch, but I have a Costco membership and I know how to use an air fryer.",
  "I saw you and immediately forgot every good pickup line I've ever read on the internet.",
  "I’m about two seconds away from asking the DJ to play something romantic, so please save us both from that.",
  "I don’t know who taught you how to smile like that, but they should be held legally responsible for the casualties.",
  "I was trying to think of something witty to say, but my internal monologue was just repeating 'don't trip, don't trip.'",
  "I’m not saying you’re the most interesting person in this room, but everybody else just faded into grey.",
  "I came over here to confirm whether you're as cool as you look, and the preliminary results are terrifyingly positive.",
  "I’d tell you that you look stunning, but I feel like you probably get tired of hearing undeniable facts.",
  "I have a terrible memory, so you might have to repeat your name about four times, but I promise I’m listening.",
  "I’m not saying I'm desperate, but my horoscope said I should make bold choices, and here you are.",
  "I saw you and thought: 'that person definitely has better taste in movies than anyone I know.'",
  "I’m not trying to brag, but I can make a mean bowl of cereal and I rarely drop things when people are watching.",
  "I came over because I realized that staying on my side of the room was yielding zero progress.",
  "I was going to make a smart remark, but looking at you feels like trying to do long division under water.",
  "I’m not saying you’re a distraction, but I was supposed to be doing my taxes tonight and now I'm here.",
  "I’d ask if you’re taken, but I’d rather live in blissful optimism for at least another thirty seconds.",
  "I saw you laughing earlier and decided that whatever made you laugh is my new favorite comedy special.",
  "I’m pretty sure my friends are taking bets right now on how fast you walk away from me.",
  "I don’t know what your weekend plans are, but I’m hoping they have a last-minute cancellation for coffee.",
  "I came over here to see if you have any flaws, and so far you're making me look really bad.",
  "I was trying to think of an excuse to talk to you, and 'I have eyes and you're gorgeous' was the only honest one.",
  "I’m not saying I'm superstitious, but walking away without your number feels like seven years of bad luck.",
  "I was told to step out of my comfort zone, and standing in front of you is about ten miles past the border.",
  "I don’t usually introduce myself like this, but you looked like you could use an entertaining conversation.",
  "I’m not saying I’m the funniest person here, but I will laugh at your jokes even when they’re objectively bad.",
  "I saw you and my inner dialogue immediately switched from 'chill mode' to 'code red.'",
  "I would offer you a witty pickup line, but I think we both know you're way too smart for that nonsense.",
  "I’m not trying to be smooth, I’m just trying to make sure I don’t leave here wondering what would’ve happened.",
  "I came over to ask what book you’re reading, or what show you’re bingeing, or literally anything that gets you talking.",
  "I was going to send my friend over to wingman for me, but he’s worse at this than I am, so you get me directly.",
  "I’m not saying you’re out of this world, but you definitely don’t fit into the average crowd here.",
  "I looked at you and realized my conversation skills were about to be put through the ultimate stress test.",
  "I’d love to buy you a coffee, but if you're an iced matcha person, please break it to me gently.",
  "I came over here because I’d rather be rejected by someone amazing than sit there wondering 'what if.'",
  "I’m not saying I’m an open book, but my face definitely has no poker filter whatsoever.",
  "I saw you and immediately decided that my original plan for the night was a complete waste of time.",
  "I’m pretty sure you just ruined every other conversation I’m going to have tonight.",
  "I don’t know what your favorite song is, but I’m ready to add it to my playlist right now.",
  "I was trying to come up with a casual way to approach you, but nothing about this feels casual.",
  "I’m not saying you’re dangerous, but my survival instincts took a complete vacation the second you walked in.",
  "I’d ask for your sign, but honestly, the only sign I need is you not walking away right now.",
  "I came over to say hello because staring at you from the corner was starting to look suspicious.",
  "I’m not trying to rush things, but I’ve already decided which of my hoodies you’re going to steal.",
  "I was going to pretend I was looking for someone else, but you're clearly the only person worth looking for.",
  "I don’t usually take big risks, but talking to you feels like a gamble where even losing is a good story.",
  "I came over because you look like the kind of person who appreciates a good, chaotic introduction.",
  "I’m not saying I have great taste, but seeing you made me feel like an absolute genius.",
  "I was trying to keep a straight face, but you looked over and my whole poker face collapsed.",
  "I’d tell you my name, but I’d rather hear what nickname you come up with after this intro.",
  "I came over here to see if your personality matches your face, and if it does, I’m in serious trouble.",
  "I don’t know what you were talking about over there, but I’m ready to take your side in any argument.",
  "I was going to play it unbothered, but honestly, you're entirely too attractive for me to pretend.",
  "I’m not saying I’m the best choice, but I will never let you watch a movie with the aspect ratio messed up.",
  "I came over because life is short, youth is temporary, and you're standing right there looking incredible.",
  "I was hoping you had a bad sense of humor so we'd have something in common right off the bat.",
  "I’m not saying you’re magical, but my plans for an early night completely vanished when you showed up.",
  "I came over to ask if you've ever had someone approach you and immediately run out of things to say, because here it is.",
  "I don’t know what kind of weekend you had, but I’d love to be the reason your week starts with a smile.",
  "I was trying to think of a good opening question, so: how do you feel about ordering too much Thai food?",
  "I’m not saying you’re my future, but you’ve definitely completely hijacked my present.",
  "I came over because I promised myself I wouldn't leave tonight without knowing who you are.",
  "I was going to wait for a mutual friend to introduce us, but neither of us knows anyone here, so hi.",
  "I’m not saying I’m a romantic, but I did just walk across this entire sticky floor just to say hello.",
  "I came over to see if you're as cool in person as you look from across the room, and yes, you definitely are.",
  "I don’t know what your plans are, but I’m officially volunteering to be the best part of them.",
  "I was going to say something profound, but honestly, you're hot, I'm awkward, and that's the whole pitch.",
  "I’m not saying you should give me a chance, but I’m really good at reaching high shelves and killing spiders.",
  "I came over because ignoring you felt like a willful act of self-sabotage.",
  "I don’t know who allowed you to look this good on a Tuesday, but they need to be recognized.",
  "I was hoping you'd look at me so I had an excuse, and then you did, and now I'm out of excuses.",
  "I’m not saying you’re trouble, but I can already tell you’re going to be expensive.",
  "I came over to ask if you believe in taking chances on strangers who clearly have no filter.",
  "I don’t know what kind of vibe you’re on tonight, but I’m ready to match it completely.",
  "I was going to try a slick pickup line, but you look like someone who’d see right through it and roast me.",
  "I’m not saying I'm great at dates, but I will split the dessert with you and let you have the bigger half.",
  "I came over because sitting over there looking at you was starting to feel like a full-time job.",
  "I don’t know what you’re having, but if it makes me look half as good as you, I’ll take two.",
  "I was trying to come up with a clever observation, but my brain is just flashing 'abort mission: too pretty.'",
  "I’m not saying you’re an angel, but you definitely look like you walked out of someone’s prayers.",
  "I came over because I'd rather tell my friends I tried and failed than spend tomorrow wondering.",
  "I don’t know what your standard is, but I’m ready to lower it with high enthusiasm.",
  "I was going to walk by you casually, but my feet made a sudden detour directly toward you.",
  "I’m not saying you’re my soulmate, but we both know this conversation was inevitable.",
  "I came over to see what kind of energy you have, and honestly, it’s completely infectious.",
  "I don’t know how you manage to stand out in a crowd this loud, but here you are.",
  "I was hoping you were approachable, and the fact that you haven't rolled your eyes yet gives me great hope.",
  "I’m not saying I’m the whole package, but the shipping is free and the reviews are mostly positive.",
  "I came over because I didn't want to regret not talking to you on the drive home.",
  "I don’t know what kind of music you like, but I’m ready to pretend I’ve been listening to it since high school.",
  "I was going to give you space, but you looked like you were waiting for someone to interrupt you.",
  "I’m not saying you’re a masterpiece, but my friends over there are definitely taking notes on you.",
  "I came over because you have the kind of laugh that makes people want to be funny.",
  "I don’t know what you're doing right now, but I hope it involves letting me introduce myself.",
  "I was trying to play it cool, but my palms are sweating and I'm pretty sure I forgot how to blink.",
  "I’m not saying you’re my destiny, but my intuition told me to get over here immediately.",
  "I came over because I’d rather be the guy who said hi than the guy who watched you leave.",
  "I don’t know what your vibe is, but I’m ready to subscribe to whatever you’re selling.",
  "I was hoping you'd give me a reason to smile tonight, and you did it before I even got over here.",
  "I’m not saying I'm your type, but I'm definitely a type you haven't tried yet.",
  "I came over because staying where I was felt like a massive mistake.",
  "I don’t know how this story goes, but I’m pretty sure this is the opening scene.",
  "I was going to say hello, but you took my breath away before I could even get the greeting out.",
  "I was going to wait for a sign, but your eyes already gave me the green light.",
  "I’m not saying I’m superstitious, but walking away right now feels like tempting fate.",
  "I came over to see if you’re as witty as you look, and I’m thoroughly intimidated already.",
  "I don't know who picked your outfit, but they deserve an award for presentation.",
  "I promised myself I’d stay out of trouble tonight, but you look like top-tier trouble.",
  "I’m not trying to be dramatic, but my week was pretty bleak until about two minutes ago.",
  "I was going to make an excuse to borrow a pen, but this isn't 1998, so can I just get your number?",
  "I came over because sitting across the room staring was starting to get me weird looks from the bartender.",
  "I don't know what kind of music makes you dance, but I'm ready to look ridiculous trying to keep up.",
  "I was going to say something suave, but then I remembered that nobody actually talks like that in real life.",
  "I’m not saying you’re an answered prayer, but my weekend plans just got a serious upgrade.",
  "I came over because life is entirely too short to wonder what kind of banter we would have had.",
  "I don't know what you were saying before I got here, but I completely agree with your stance on the issue.",
  "I was going to play the long game, but I'm impatient and you're stunning.",
  "I’m not saying I’m the prize here, but I will never steal your French fries without asking.",
  "I’m ready to bet that getting your number is the smartest thing I'll do all week."
];

funnyLines.forEach(text => add('funny', text));

// -------------------------------------------------------------
// FOODIE (60 lines) - Tasty culinary puns, drink & coffee wit
// -------------------------------------------------------------
const foodieLines = [
  "Are you a barista? Because you've bean on my mind all day.",
  "Are you pizza? Because even when you're bad, you're still pretty amazing.",
  "You must be made of cinnamon and sugar, because you are un-snickerdoodly sweet.",
  "Are you tacos? Because every day with you feels like Tuesday.",
  "If you were a burger at McDonald's, you'd be the McGorgeous.",
  "Are you French fries? Because I can't keep my hands off you.",
  "Are you spicy ramen? Because you’ve got me sweating and wanting more.",
  "Are you a pastry? Because you've got layers of sweetness.",
  "Do you like sushi? Because I'm soy into you.",
  "Are you a waffle? Because I like you a waffle lot.",
  "Are you chocolate cake? Because one taste of your smile is never enough.",
  "If you were an avocado, you'd be the good fat that makes everything better.",
  "Are you a hot cup of matcha? Because you bring pure zen to my chaos.",
  "Are you a donut? Because I find you a-dough-rable.",
  "Do you work at a bakery? Because you’ve got the sweetest buns in town.",
  "Are you guacamole? Because I know you're extra, and I'm willing to pay.",
  "Are you a chili pepper? Because you're adding some serious heat to this room.",
  "If you were a fruit, you'd be a fine-apple with zero competition.",
  "Are you honey? Because you stick to my thoughts all day long.",
  "Do you like pasta? Because I cannoli be happy when you're around.",
  "Are you iced boba? Because you're sweet, refreshing, and full of good surprises.",
  "Are you an espresso shot? Because you've got my heart racing at double speed.",
  "If you were cheese, you'd be gouda, because you look great today.",
  "Are you a cookie fresh out of the oven? Because you melt my heart right away.",
  "Are you barbecue sauce? Because you make everything taste ten times better.",
  "Do you like breakfast food? Because I'd love to pancake you in my arms.",
  "Are you a strawberry? Because you're berry special to me.",
  "Are you a fine vintage wine? Because you're intoxicating and getting better with time.",
  "If you were a dish at a 5-star restaurant, you'd be the chef's tasting menu.",
  "Are you a croissant? Because you're golden, flaky, and buttery smooth.",
  "Are you garlic bread? Because you're the best part of the whole meal.",
  "Do you like Mexican food? Because I want to taco 'bout our future.",
  "Are you a milk tea? Because life without you is just plain water.",
  "Are you a scoop of gelato? Because you're rich, sweet, and made for summer days.",
  "If you were a condiment, you'd be sriracha because you make everything spicy.",
  "Are you hot cocoa with marshmallows? Because you're pure comfort in a cup.",
  "Do you like brunch? Because spending Sunday mornings with you sounds like paradise.",
  "Are you a bag of chips? Because once I start talking to you, I can't stop.",
  "Are you a grilled cheese? Because you make everything warm and gooey inside.",
  "If you were an ice cream flavor, you'd be salted caramel: sweet with a little edge.",
  "Are you a sourdough starter? Because my affection for you keeps rising every day.",
  "Do you like fondue? Because I'm melting all over you.",
  "Are you a glass of champagne? Because you make every Tuesday feel like New Year's Eve.",
  "If you were a pizza topping, you'd be extra cheese because you're indulgent.",
  "Are you a coffee bean? Because you grind my gears in the best way possible.",
  "Do you like dumplings? Because you're filled with absolute perfection.",
  "Are you a mango? Because you make my tropical dreams come true.",
  "If you were a pretzel, you'd be warm, salty, and twisted with charm.",
  "Are you a bowl of cereal? Because you're the first thing I want in the morning.",
  "Do you like churros? Because you're dusted with sweetness and hot as can be.",
  "Are you an olive in a martini? Because you're the classy finish to my evening.",
  "If you were soup, you'd be chicken noodle because you heal all my bad days.",
  "Are you a peach? Because you're fuzzy, sweet, and Georgia fine.",
  "Do you like hot pot? Because sitting across from you is an experience I crave.",
  "Are you a French crepe? Because you're delicate, sweet, and irresistible.",
  "If you were dessert, you'd be molten lava cake: explosive and sweet.",
  "Are you cotton candy? Because you dissolve all my worries with one sweet smile.",
  "Do you like dim sum? Because you've steamed up my whole evening.",
  "Are you an artisanal coffee? Because you're crafted with unmatched care.",
  "If you were a feast, you'd be Thanksgiving dinner: worth waiting all year for."
];

foodieLines.forEach(text => add('foodie', text));

// -------------------------------------------------------------
// CLEVER (60 lines) - Sharp wordplay, double entendres, logic
// -------------------------------------------------------------
const cleverLines = [
  "If you were words on a page, you'd be what they call fine print.",
  "Are you an art gallery? Because I could admire you for hours without saying a word.",
  "I'd never play hide and seek with you, because someone like you is impossible to find.",
  "Do you have a name, or can I call you mine?",
  "You must be a 90-degree angle, because to me, you're looking just right.",
  "If conversation were currency, I’d invest my entire savings into talking with you.",
  "Most people look for four-leaf clovers, but finding you feels like skipping straight to the pot of gold.",
  "If tension were electricity, standing this close to you would shut down the city grid.",
  "We haven’t even said two words to each other, and there’s already enough heat here to start a wildfire.",
  "They say nothing lasts forever, so let's be each other's bad habit starting tonight.",
  "I’m not a mathematician, but I know when two variables belong together.",
  "Are you a shadow? Because even in the dark, you stick right by my side.",
  "If beauty was knowledge, you'd have a PhD with honors.",
  "I’d tell you what I'm thinking, but I'd rather show you over dinner.",
  "Are you a silent letter? Because even when you're quiet, you change everything.",
  "If charm had an interest rate, you'd be compounding by the second.",
  "You're the kind of question I don't ever want a simple answer to.",
  "Are you an unspoken rule? Because everyone feels your presence without being told.",
  "If words could paint, your name would be the whole canvas.",
  "I don't need a telescope to know you're the center of my galaxy.",
  "Are you an ellipsis? Because every time you speak, I'm waiting for what's next...",
  "If elegance was a language, you'd be fluent in every dialect.",
  "You're like an open-ended book: every chapter keeps getting better.",
  "Are you a rare edition? Because there isn't another copy of you anywhere.",
  "If confidence had a silhouette, it would match your posture perfectly.",
  "I'm not playing games, but I know a winning move when I see one.",
  "Are you a double negative? Because two wrongs don't make a right, but we make complete sense.",
  "If attraction was physics, we’d be breaking Einstein’s laws of gravity.",
  "You're the puzzle piece that doesn't just fit—it completes the picture.",
  "Are you an echo in an empty hall? Because you linger long after you speak.",
  "If charm was a crime, you wouldn't even be eligible for bail.",
  "You carry an intellect that makes your beauty twice as dangerous.",
  "Are you a rare frequency? Because you resonate at a wavelength nobody else touches.",
  "If silence speaks volumes, looking at you is an entire library.",
  "You don't just turn heads; you redirect whole lives.",
  "Are you a paradox? Because the more I look, the less I can explain how good you are.",
  "If intuition was an art, my gut feeling about you would hang in the Louvre.",
  "You make confidence look like second nature.",
  "Are you a master key? Because you unlocked thoughts I didn't know I had.",
  "If beauty had a soundtrack, you'd be a symphonic crescendo.",
  "You're not an option; you're the priority.",
  "Are you an optical illusion? Because reality never looked this sharp.",
  "If wit was fire, talking to you would require a hazard warning.",
  "You carry a mystery that makes curiosity irresistible.",
  "Are you a timeless melody? Because every era would have loved you.",
  "If grace had a measure, you'd exceed the standard deviation.",
  "You're the spark that turns an ordinary conversation into an adventure.",
  "Are you a prism? Because you turn simple moments into a spectrum of fun.",
  "If I could quote you, you'd be the headline of my year.",
  "You have an effortless intelligence that draws people in like gravity.",
  "Are you a signature style? Because nobody wears confidence quite like you.",
  "If charm was a currency, you'd have your face printed on the bill.",
  "You're the kind of paradox that makes total sense in person.",
  "Are you a compass needle? Because true north just shifted to your smile.",
  "If looking good was a discipline, you'd be a tenured professor.",
  "You have a cadence that makes listening the easiest thing in the world.",
  "Are you a rare gem? Because people spend lifetimes searching for someone like you.",
  "If intrigue was measurable, you'd break every barometer in the room.",
  "You make the art of conversation feel like high-stakes chess.",
  "I don't need luck when I've got the chance to make you smile."
];

cleverLines.forEach(text => add('clever', text));

// Output counts
const counts: Record<string, number> = {};
rawDataset.forEach(l => {
  counts[l.category] = (counts[l.category] || 0) + 1;
});

console.log('=== DATASET GENERATION SUMMARY ===');
console.log(counts);
console.log(`TOTAL LINES GENERATED: ${rawDataset.length}`);

// Write JSON dataset
const outputDir = path.join(process.cwd(), 'src', 'data');
const outputFile = path.join(outputDir, 'pickupLinesMaster.json');

fs.writeFileSync(outputFile, JSON.stringify(rawDataset, null, 2), 'utf-8');
console.log(`Saved master dataset to: ${outputFile}`);
